-- Users table seeds here (Example)
INSERT INTO chapters (title, body, published) VALUES ('Chapter I', 'When we started for our drive the sun was shining brightly on Munich, and the air was full of the joyousness of early summer. Just as we were about to depart, Herr Delbrück (the maître d’hôtel of the Quatre Saisons, where I was staying) came down, bareheaded, to the carriage and, after wishing me a pleasant drive, said to the coachman, still holding his hand on the handle of the carriage door:
“Remember you are back by nightfall. The sky looks bright but there is a shiver in the north wind that says there may be a sudden storm. But I am sure you will not be late.” Here he smiled, and added, “for you know what night it is.”
Johann answered with an emphatic, “Ja, mein Herr,” and, touching his hat, drove off quickly. When we had cleared the town, I said, after signalling to him to stop:
“Tell me, Johann, what is tonight?”
He crossed himself, as he answered laconically: “Walpurgis nacht.” Then he took out his watch, a great, old-fashioned German silver thing as big as a turnip, and looked at it, with his eyebrows gathered together and a little impatient shrug of his shoulders. I realised that this was his way of respectfully protesting against the unnecessary delay, and sank back in the carriage, merely motioning him to proceed. He started off rapidly, as if to make up for lost time. Every now and then the horses seemed to throw up their heads and sniffed the air suspiciously. On such occasions I often looked round in alarm. The road was pretty bleak, for we were traversing a sort of high, wind-swept plateau. As we drove, I saw a road that looked but little used, and which seemed to dip through a little, winding valley. It looked so inviting that, even at the risk of offending him, I called Johann to stop—and when he had pulled up, I told him I would like to drive down that road. He made all sorts of excuses, and frequently crossed himself as he spoke. This somewhat piqued my curiosity, so I asked him various questions. He answered fencingly, and repeatedly looked at his watch in protest. Finally I said:
“Well, Johann, I want to go down this road. I shall not ask you to come unless you like; but tell me why you do not like to go, that is all I ask.” For answer he seemed to throw himself off the box, so quickly did he reach the ground. Then he stretched out his hands appealingly to me, and implored me not to go. There was just enough of English mixed with the German for me to understand the drift of his talk. He seemed always just about to tell me something—the very idea of which evidently frightened him; but each time he pulled himself up, saying, as he crossed himself: “Walpurgis-Nacht!”', true);

INSERT INTO chapters (title, body, published) VALUES ('Chapter II', 'I tried to argue with him, but it was difficult to argue with a man when I did not know his language. The advantage certainly rested with him, for although he began to speak in English, of a very crude and broken kind, he always got excited and broke into his native tongue—and every time he did so, he looked at his watch. Then the horses became restless and sniffed the air. At this he grew very pale, and, looking around in a frightened way, he suddenly jumped forward, took them by the bridles and led them on some twenty feet. I followed, and asked why he had done this. For answer he crossed himself, pointed to the spot we had left and drew his carriage in the direction of the other road, indicating a cross, and said, first in German, then in English: “Buried him—him what killed themselves.”
I remembered the old custom of burying suicides at cross-roads: “Ah! I see, a suicide. How interesting!” But for the life of me I could not make out why the horses were frightened.
Whilst we were talking, we heard a sort of sound between a yelp and a bark. It was far away; but the horses got very restless, and it took Johann all his time to quiet them. He was pale, and said, “It sounds like a wolf—but yet there are no wolves here now.”
“No?” I said, questioning him; “isn’t it long since the wolves were so near the city?”
“Long, long,” he answered, “in the spring and summer; but with the snow the wolves have been here not so long.”
Whilst he was petting the horses and trying to quiet them, dark clouds drifted rapidly across the sky. The sunshine passed away, and a breath of cold wind seemed to drift past us. It was only a breath, however, and more in the nature of a warning than a fact, for the sun came out brightly again. Johann looked under his lifted hand at the horizon and said:
“The storm of snow, he comes before long time.” Then he looked at his watch again, and, straightway holding his reins firmly—for the horses were still pawing the ground restlessly and shaking their heads—he climbed to his box as though the time had come for proceeding on our journey.', true);

INSERT INTO chapters (title, body, published) VALUES ('Chapter III', 'I felt a little obstinate and did not at once get into the carriage.
“Tell me,” I said, “about this place where the road leads,” and I pointed down.
Again he crossed himself and mumbled a prayer, before he answered, “It is unholy.”
“What is unholy?” I enquired.
“The village.”
“Then there is a village?”
“No, no. No one lives there hundreds of years.” My curiosity was piqued, “But you said there was a village.”
“There was.”
“Where is it now?”
Whereupon he burst out into a long story in German and English, so mixed up that I could not quite understand exactly what he said, but roughly I gathered that long ago, hundreds of years, men had died there and been buried in their graves; and sounds were heard under the clay, and when the graves were opened, men and women were found rosy with life, and their mouths red with blood. And so, in haste to save their lives (aye, and their souls!—and here he crossed himself) those who were left fled away to other places, where the living lived, and the dead were dead and not—not something. He was evidently afraid to speak the last words. As he proceeded with his narration, he grew more and more excited. It seemed as if his imagination had got hold of him, and he ended in a perfect paroxysm of fear—white-faced, perspiring, trembling and looking round him, as if expecting that some dreadful presence would manifest itself there in the bright sunshine on the open plain. Finally, in an agony of desperation, he cried:
“Walpurgis nacht!” and pointed to the carriage for me to get in. All my English blood rose at this, and, standing back, I said:
“You are afraid, Johann—you are afraid. Go home; I shall return alone; the walk will do me good.” The carriage door was open. I took from the seat my oak walking-stick—which I always carry on my holiday excursions—and closed the door, pointing back to Munich, and said, “Go home, Johann—Walpurgis-nacht doesn’t concern Englishmen.”
The horses were now more restive than ever, and Johann was trying to hold them in, while excitedly imploring me not to do anything so foolish. I pitied the poor fellow, he was deeply in earnest; but all the same I could not help laughing. His English was quite gone now. In his anxiety he had forgotten that his only means of making me understand was to talk my language, so he jabbered away in his native German. It began to be a little tedious. After giving the direction, “Home!” I turned to go down the cross-road into the valley.
With a despairing gesture, Johann turned his horses towards Munich. I leaned on my stick and looked after him. He went slowly along the road for a while: then there came over the crest of the hill a man tall and thin. I could see so much in the distance. When he drew near the horses, they began to jump and kick about, then to scream with terror. Johann could not hold them in; they bolted down the road, running away madly. I watched them out of sight, then looked for the stranger, but I found that he, too, was gone.', true);

INSERT INTO chapters (title, body, published) VALUES ('Chapter 1', ' I am by birth a Genevese, and my family is one of the most distinguished of that republic. My ancestors had been for many years counsellors and syndics, and my father had filled several public situations with honour and reputation. He was respected by all who knew him for his integrity and indefatigable attention to public business. He passed his younger days perpetually occupied by the affairs of his country; a variety of circumstances had prevented his marrying early, nor was it until the decline of life that he became a husband and the father of a family. As the circumstances of his marriage illustrate his character, I cannot refrain from relating them. One of his most intimate friends was a merchant who, from a flourishing state, fell, through numerous mischances, into poverty. This man, whose name was Beaufort, was of a proud and unbending disposition and could not bear to live in poverty and oblivion in the same country where he had formerly been distinguished for his rank and magnificence. Having paid his debts, therefore, in the most honourable manner, he retreated with his daughter to the town of Lucerne, where he lived unknown and in wretchedness. My father loved Beaufort with the truest friendship and was deeply grieved by his retreat in these unfortunate circumstances. He bitterly deplored the false pride which led his friend to a conduct so little worthy of the affection that united them. He lost no time in endeavouring to seek him out, with the hope of persuading him to begin the world again through his credit and assistance.
Beaufort had taken effectual measures to conceal himself, and it was ten months before my father discovered his abode. Overjoyed at this discovery, he hastened to the house, which was situated in a mean street near the Reuss. But when he entered, misery and despair alone welcomed him. Beaufort had saved but a very small sum of money from the wreck of his fortunes, but it was sufficient to provide him with sustenance for some months, and in the meantime he hoped to procure some respectable employment in a merchant’s house. The interval was, consequently, spent in inaction; his grief only became more deep and rankling when he had leisure for reflection, and at length it took so fast hold of his mind that at the end of three months he lay on a bed of sickness, incapable of any exertion.
His daughter attended him with the greatest tenderness, but she saw with despair that their little fund was rapidly decreasing and that there was no other prospect of support. But Caroline Beaufort possessed a mind of an uncommon mould, and her courage rose to support her in her adversity. She procured plain work; she plaited straw and by various means contrived to earn a pittance scarcely sufficient to support life.
Several months passed in this manner. Her father grew worse; her time was more entirely occupied in attending him; her means of subsistence decreased; and in the tenth month her father died in her arms, leaving her an orphan and a beggar. This last blow overcame her, and she knelt by Beaufort’s coffin weeping bitterly, when my father entered the chamber. He came like a protecting spirit to the poor girl, who committed herself to his care; and after the interment of his friend he conducted her to Geneva and placed her under the protection of a relation. Two years after this event Caroline became his wife.
There was a considerable difference between the ages of my parents, but this circumstance seemed to unite them only closer in bonds of devoted affection. There was a sense of justice in my father’s upright mind which rendered it necessary that he should approve highly to love strongly. Perhaps during former years he had suffered from the late-discovered unworthiness of one beloved and so was disposed to set a greater value on tried worth. There was a show of gratitude and worship in his attachment to my mother, differing wholly from the doting fondness of age, for it was inspired by reverence for her virtues and a desire to be the means of, in some degree, recompensing her for the sorrows she had endured, but which gave inexpressible grace to his behaviour to her. Everything was made to yield to her wishes and her convenience. He strove to shelter her, as a fair exotic is sheltered by the gardener, from every rougher wind and to surround her with all that could tend to excite pleasurable emotion in her soft and benevolent mind. Her health, and even the tranquillity of her hitherto constant spirit, had been shaken by what she had gone through. During the two years that had elapsed previous to their marriage my father had gradually relinquished all his public functions; and immediately after their union they sought the pleasant climate of Italy, and the change of scene and interest attendant on a tour through that land of wonders, as a restorative for her weakened frame.
From Italy they visited Germany and France. I, their eldest child, was born at Naples, and as an infant accompanied them in their rambles. I remained for several years their only child. Much as they were attached to each other, they seemed to draw inexhaustible stores of affection from a very mine of love to bestow them upon me. My mother’s tender caresses and my father’s smile of benevolent pleasure while regarding me are my first recollections. I was their plaything and their idol, and something better—their child, the innocent and helpless creature bestowed on them by Heaven, whom to bring up to good, and whose future lot it was in their hands to direct to happiness or misery, according as they fulfilled their duties towards me. With this deep consciousness of what they owed towards the being to which they had given life, added to the active spirit of tenderness that animated both, it may be imagined that while during every hour of my infant life I received a lesson of patience, of charity, and of self-control, I was so guided by a silken cord that all seemed but one train of enjoyment to me.
For a long time I was their only care. My mother had much desired to have a daughter, but I continued their single offspring. When I was about five years old, while making an excursion beyond the frontiers of Italy, they passed a week on the shores of the Lake of Como. Their benevolent disposition often made them enter the cottages of the poor. This, to my mother, was more than a duty; it was a necessity, a passion—remembering what she had suffered, and how she had been relieved—for her to act in her turn the guardian angel to the afflicted. During one of their walks a poor cot in the foldings of a vale attracted their notice as being singularly disconsolate, while the number of half-clothed children gathered about it spoke of penury in its worst shape. One day, when my father had gone by himself to Milan, my mother, accompanied by me, visited this abode. She found a peasant and his wife, hard working, bent down by care and labour, distributing a scanty meal to five hungry babes. Among these there was one which attracted my mother far above all the rest. She appeared of a different stock. The four others were dark-eyed, hardy little vagrants; this child was thin and very fair. Her hair was the brightest living gold, and despite the poverty of her clothing, seemed to set a crown of distinction on her head. Her brow was clear and ample, her blue eyes cloudless, and her lips and the moulding of her face so expressive of sensibility and sweetness that none could behold her without looking on her as of a distinct species, a being heaven-sent, and bearing a celestial stamp in all her features.
The peasant woman, perceiving that my mother fixed eyes of wonder and admiration on this lovely girl, eagerly communicated her history. She was not her child, but the daughter of a Milanese nobleman. Her mother was a German and had died on giving her birth. The infant had been placed with these good people to nurse: they were better off then. They had not been long married, and their eldest child was but just born. The father of their charge was one of those Italians nursed in the memory of the antique glory of Italy—one among the schiavi ognor frementi, who exerted himself to obtain the liberty of his country. He became the victim of its weakness. Whether he had died or still lingered in the dungeons of Austria was not known. His property was confiscated; his child became an orphan and a beggar. She continued with her foster parents and bloomed in their rude abode, fairer than a garden rose among dark-leaved brambles.
When my father returned from Milan, he found playing with me in the hall of our villa a child fairer than pictured cherub—a creature who seemed to shed radiance from her looks and whose form and motions were lighter than the chamois of the hills. The apparition was soon explained. With his permission my mother prevailed on her rustic guardians to yield their charge to her. They were fond of the sweet orphan. Her presence had seemed a blessing to them, but it would be unfair to her to keep her in poverty and want when Providence afforded her such powerful protection. They consulted their village priest, and the result was that Elizabeth Lavenza became the inmate of my parents’ house—my more than sister—the beautiful and adored companion of all my occupations and my pleasures.
Everyone loved Elizabeth. The passionate and almost reverential attachment with which all regarded her became, while I shared it, my pride and my delight. On the evening previous to her being brought to my home, my mother had said playfully, “I have a pretty present for my Victor—tomorrow he shall have it.” And when, on the morrow, she presented Elizabeth to me as her promised gift, I, with childish seriousness, interpreted her words literally and looked upon Elizabeth as mine—mine to protect, love, and cherish. All praises bestowed on her I received as made to a possession of my own. We called each other familiarly by the name of cousin. No word, no expression could body forth the kind of relation in which she stood to me—my more than sister, since till death she was to be mine only.', true);

INSERT INTO chapters (title, body, published) VALUES ('Chapter 2', ' We were brought up together; there was not quite a year difference in our ages. I need not say that we were strangers to any species of disunion or dispute. Harmony was the soul of our companionship, and the diversity and contrast that subsisted in our characters drew us nearer together. Elizabeth was of a calmer and more concentrated disposition; but, with all my ardour, I was capable of a more intense application and was more deeply smitten with the thirst for knowledge. She busied herself with following the aerial creations of the poets; and in the majestic and wondrous scenes which surrounded our Swiss home —the sublime shapes of the mountains, the changes of the seasons, tempest and calm, the silence of winter, and the life and turbulence of our Alpine summers—she found ample scope for admiration and delight. While my companion contemplated with a serious and satisfied spirit the magnificent appearances of things, I delighted in investigating their causes. The world was to me a secret which I desired to divine. Curiosity, earnest research to learn the hidden laws of nature, gladness akin to rapture, as they were unfolded to me, are among the earliest sensations I can remember.
On the birth of a second son, my junior by seven years, my parents gave up entirely their wandering life and fixed themselves in their native country. We possessed a house in Geneva, and a campagne on Belrive, the eastern shore of the lake, at the distance of rather more than a league from the city. We resided principally in the latter, and the lives of my parents were passed in considerable seclusion. It was my temper to avoid a crowd and to attach myself fervently to a few. I was indifferent, therefore, to my school-fellows in general; but I united myself in the bonds of the closest friendship to one among them. Henry Clerval was the son of a merchant of Geneva. He was a boy of singular talent and fancy. He loved enterprise, hardship, and even danger for its own sake. He was deeply read in books of chivalry and romance. He composed heroic songs and began to write many a tale of enchantment and knightly adventure. He tried to make us act plays and to enter into masquerades, in which the characters were drawn from the heroes of Roncesvalles, of the Round Table of King Arthur, and the chivalrous train who shed their blood to redeem the holy sepulchre from the hands of the infidels.
No human being could have passed a happier childhood than myself. My parents were possessed by the very spirit of kindness and indulgence. We felt that they were not the tyrants to rule our lot according to their caprice, but the agents and creators of all the many delights which we enjoyed. When I mingled with other families I distinctly discerned how peculiarly fortunate my lot was, and gratitude assisted the development of filial love.
My temper was sometimes violent, and my passions vehement; but by some law in my temperature they were turned not towards childish pursuits but to an eager desire to learn, and not to learn all things indiscriminately. I confess that neither the structure of languages, nor the code of governments, nor the politics of various states possessed attractions for me. It was the secrets of heaven and earth that I desired to learn; and whether it was the outward substance of things or the inner spirit of nature and the mysterious soul of man that occupied me, still my inquiries were directed to the metaphysical, or in its highest sense, the physical secrets of the world.', true);

INSERT INTO chapters (title, body) VALUES ('Chapter 2', '  Meanwhile Clerval occupied himself, so to speak, with the moral relations of things. The busy stage of life, the virtues of heroes, and the actions of men were his theme; and his hope and his dream was to become one among those whose names are recorded in story as the gallant and adventurous benefactors of our species. The saintly soul of Elizabeth shone like a shrine-dedicated lamp in our peaceful home. Her sympathy was ours; her smile, her soft voice, the sweet glance of her celestial eyes, were ever there to bless and animate us. She was the living spirit of love to soften and attract; I might have become sullen in my study, rough through the ardour of my nature, but that she was there to subdue me to a semblance of her own gentleness. And Clerval—could aught ill entrench on the noble spirit of Clerval? Yet he might not have been so perfectly humane, so thoughtful in his generosity, so full of kindness and tenderness amidst his passion for adventurous exploit, had she not unfolded to him the real loveliness of beneficence and made the doing good the end and aim of his soaring ambition.
I feel exquisite pleasure in dwelling on the recollections of childhood, before misfortune had tainted my mind and changed its bright visions of extensive usefulness into gloomy and narrow reflections upon self. Besides, in drawing the picture of my early days, I also record those events which led, by insensible steps, to my after tale of misery, for when I would account to myself for the birth of that passion which afterwards ruled my destiny I find it arise, like a mountain river, from ignoble and almost forgotten sources; but, swelling as it proceeded, it became the torrent which, in its course, has swept away all my hopes and joys.
Natural philosophy is the genius that has regulated my fate; I desire, therefore, in this narration, to state those facts which led to my predilection for that science. When I was thirteen years of age we all went on a party of pleasure to the baths near Thonon; the inclemency of the weather obliged us to remain a day confined to the inn. In this house I chanced to find a volume of the works of Cornelius Agrippa. I opened it with apathy; the theory which he attempts to demonstrate and the wonderful facts which he relates soon changed this feeling into enthusiasm. A new light seemed to dawn upon my mind, and bounding with joy, I communicated my discovery to my father. My father looked carelessly at the title page of my book and said, “Ah! Cornelius Agrippa! My dear Victor, do not waste your time upon this; it is sad trash.” ');

INSERT INTO chapters (title, body, published) VALUES ('',
'Once upon a midnight dreary, while I pondered, weak and weary,
Over many a quaint and curious volume of forgotten lore—
    While I nodded, nearly napping, suddenly there came a tapping,
As of some one gently rapping, rapping at my chamber door.
“’Tis some visitor,” I muttered, “tapping at my chamber door—
            Only this and nothing more.”

    Ah, distinctly I remember it was in the bleak December;
And each separate dying ember wrought its ghost upon the floor.
    Eagerly I wished the morrow;—vainly I had sought to borrow
    From my books surcease of sorrow—sorrow for the lost Lenore—
For the rare and radiant maiden whom the angels name Lenore—
            Nameless here for evermore.', true);

INSERT INTO chapters (title, body, published) VALUES ('',
'And the silken, sad, uncertain rustling of each purple curtain
Thrilled me—filled me with fantastic terrors never felt before;
    So that now, to still the beating of my heart, I stood repeating
    “’Tis some visitor entreating entrance at my chamber door—
Some late visitor entreating entrance at my chamber door;—
            This it is and nothing more.”

    Presently my soul grew stronger; hesitating then no longer,
“Sir,” said I, “or Madam, truly your forgiveness I implore;
    But the fact is I was napping, and so gently you came rapping,
    And so faintly you came tapping, tapping at my chamber door,
That I scarce was sure I heard you”—here I opened wide the door;—
            Darkness there and nothing more.', false);

/* new entry */
INSERT INTO chapters (title, body, published) VALUES ('Chapter IV', 'With a light heart I turned down the side road through the deepening valley to which Johann had objected. There was not the slightest reason, that I could see, for his objection; and I daresay I tramped for a couple of hours without thinking of time or distance, and certainly without seeing a person or a house. So far as the place was concerned, it was desolation itself. But I did not notice this particularly till, on turning a bend in the road, I came upon a scattered fringe of wood; then I recognised that I had been impressed unconsciously by the desolation of the region through which I had passed.
I sat down to rest myself, and began to look around. It struck me that it was considerably colder than it had been at the commencement of my walk—a sort of sighing sound seemed to be around me, with, now and then, high overhead, a sort of muffled roar. Looking upwards I noticed that great thick clouds were drifting rapidly across the sky from North to South at a great height. There were signs of coming storm in some lofty stratum of the air. I was a little chilly, and, thinking that it was the sitting still after the exercise of walking, I resumed my journey.', true);
